# Goal specifies the state command and strategy in case of switch failure
m3meka_msgs/M3ControlStates command

int32 strategy
int32 BEST_POSSIBLE=1
int32 HALT_ON_FAILURE=2
int32 RETRY_N_TIMES=3
int32 KEEP_TRYING=4

uint32 retries
---
# Result show state
m3meka_msgs/M3ControlStates result
---
# Feedback: current group and its change attempt and total number of groups successfully changed
string  current_group
uint32  change_attempt
uint32  group_already_changed
