# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3HANDUASTATUS = descriptor.Descriptor(
  name='M3HandUAStatus',
  full_name='M3HandUAStatus',
  filename='hand_ua.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3HandUAStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_thumb', full_name='M3HandUAStatus.theta_thumb', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_index', full_name='M3HandUAStatus.theta_index', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_ring', full_name='M3HandUAStatus.theta_ring', index=3,
      number=4, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta_pinky', full_name='M3HandUAStatus.theta_pinky', index=4,
      number=5, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3HANDUACOMMAND = descriptor.Descriptor(
  name='M3HandUACommand',
  full_name='M3HandUACommand',
  filename='hand_ua.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3HandUACommand.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3HANDUAPARAM = descriptor.Descriptor(
  name='M3HandUAParam',
  full_name='M3HandUAParam',
  filename='hand_ua.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='flex_factor_thumb', full_name='M3HandUAParam.flex_factor_thumb', index=0,
      number=1, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flex_factor_index', full_name='M3HandUAParam.flex_factor_index', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flex_factor_ring', full_name='M3HandUAParam.flex_factor_ring', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flex_factor_pinky', full_name='M3HandUAParam.flex_factor_pinky', index=3,
      number=4, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2

_M3HANDUASTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS

class M3HandUAStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HANDUASTATUS

class M3HandUACommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HANDUACOMMAND

class M3HandUAParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HANDUAPARAM

