# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3HUMANOIDSHMSTATUS = descriptor.Descriptor(
  name='M3HumanoidShmStatus',
  full_name='M3HumanoidShmStatus',
  filename='humanoid_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3HumanoidShmStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='test', full_name='M3HumanoidShmStatus.test', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3HUMANOIDSHMCOMMAND = descriptor.Descriptor(
  name='M3HumanoidShmCommand',
  full_name='M3HumanoidShmCommand',
  filename='humanoid_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3HumanoidShmCommand.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3HUMANOIDSHMPARAM = descriptor.Descriptor(
  name='M3HumanoidShmParam',
  full_name='M3HumanoidShmParam',
  filename='humanoid_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3HumanoidShmParam.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2

_M3HUMANOIDSHMSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS

class M3HumanoidShmStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HUMANOIDSHMSTATUS

class M3HumanoidShmCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HUMANOIDSHMCOMMAND

class M3HumanoidShmParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HUMANOIDSHMPARAM

