# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3HUMANOIDSTATUS = descriptor.Descriptor(
  name='M3HumanoidStatus',
  full_name='M3HumanoidStatus',
  filename='humanoid.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3HumanoidStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_arm', full_name='M3HumanoidStatus.right_arm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_arm', full_name='M3HumanoidStatus.left_arm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torso', full_name='M3HumanoidStatus.torso', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='M3HumanoidStatus.head', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_eye_rot', full_name='M3HumanoidStatus.right_eye_rot', index=5,
      number=6, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_eye_rot', full_name='M3HumanoidStatus.left_eye_rot', index=6,
      number=7, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_eye_pos', full_name='M3HumanoidStatus.right_eye_pos', index=7,
      number=8, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_eye_pos', full_name='M3HumanoidStatus.left_eye_pos', index=8,
      number=9, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='motor_enabled', full_name='M3HumanoidStatus.motor_enabled', index=9,
      number=10, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3HUMANOIDCOMMAND = descriptor.Descriptor(
  name='M3HumanoidCommand',
  full_name='M3HumanoidCommand',
  filename='humanoid.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='right_arm', full_name='M3HumanoidCommand.right_arm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_arm', full_name='M3HumanoidCommand.left_arm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torso', full_name='M3HumanoidCommand.torso', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='M3HumanoidCommand.head', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='enable_motor', full_name='M3HumanoidCommand.enable_motor', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3HUMANOIDPARAM = descriptor.Descriptor(
  name='M3HumanoidParam',
  full_name='M3HumanoidParam',
  filename='humanoid.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='right_arm', full_name='M3HumanoidParam.right_arm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_arm', full_name='M3HumanoidParam.left_arm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torso', full_name='M3HumanoidParam.torso', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='M3HumanoidParam.head', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3BASEHUMANOIDSTATUS = descriptor.Descriptor(
  name='M3BaseHumanoidStatus',
  full_name='M3BaseHumanoidStatus',
  filename='humanoid.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='torque', full_name='M3BaseHumanoidStatus.torque', index=0,
      number=1, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torquedot', full_name='M3BaseHumanoidStatus.torquedot', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta', full_name='M3BaseHumanoidStatus.theta', index=2,
      number=4, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadot', full_name='M3BaseHumanoidStatus.thetadot', index=3,
      number=5, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadotdot', full_name='M3BaseHumanoidStatus.thetadotdot', index=4,
      number=6, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='completed_spline_idx', full_name='M3BaseHumanoidStatus.completed_spline_idx', index=5,
      number=7, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_pos', full_name='M3BaseHumanoidStatus.end_pos', index=6,
      number=8, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_rot', full_name='M3BaseHumanoidStatus.end_rot', index=7,
      number=9, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='J', full_name='M3BaseHumanoidStatus.J', index=8,
      number=10, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='G', full_name='M3BaseHumanoidStatus.G', index=9,
      number=11, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_twist', full_name='M3BaseHumanoidStatus.end_twist', index=10,
      number=12, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pwm_cmd', full_name='M3BaseHumanoidStatus.pwm_cmd', index=11,
      number=13, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3BASEHUMANOIDCOMMAND = descriptor.Descriptor(
  name='M3BaseHumanoidCommand',
  full_name='M3BaseHumanoidCommand',
  filename='humanoid.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tq_desired', full_name='M3BaseHumanoidCommand.tq_desired', index=0,
      number=1, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_stiffness', full_name='M3BaseHumanoidCommand.q_stiffness', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ctrl_mode', full_name='M3BaseHumanoidCommand.ctrl_mode', index=2,
      number=3, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_desired', full_name='M3BaseHumanoidCommand.q_desired', index=3,
      number=4, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vias', full_name='M3BaseHumanoidCommand.vias', index=4,
      number=5, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qdot_desired', full_name='M3BaseHumanoidCommand.qdot_desired', index=5,
      number=6, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_slew_rate', full_name='M3BaseHumanoidCommand.q_slew_rate', index=6,
      number=7, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pwm_desired', full_name='M3BaseHumanoidCommand.pwm_desired', index=7,
      number=8, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='smoothing_mode', full_name='M3BaseHumanoidCommand.smoothing_mode', index=8,
      number=9, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3BASEHUMANOIDPARAM = descriptor.Descriptor(
  name='M3BaseHumanoidParam',
  full_name='M3BaseHumanoidParam',
  filename='humanoid.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='payload_mass', full_name='M3BaseHumanoidParam.payload_mass', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload_com', full_name='M3BaseHumanoidParam.payload_com', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload_inertia', full_name='M3BaseHumanoidParam.payload_inertia', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='use_velocities', full_name='M3BaseHumanoidParam.use_velocities', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='use_accelerations', full_name='M3BaseHumanoidParam.use_accelerations', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2
import joint_array_mode_pb2
import trajectory_pb2
import smoothing_mode_pb2

_M3HUMANOIDSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3HUMANOIDSTATUS.fields_by_name['right_arm'].message_type = _M3BASEHUMANOIDSTATUS
_M3HUMANOIDSTATUS.fields_by_name['left_arm'].message_type = _M3BASEHUMANOIDSTATUS
_M3HUMANOIDSTATUS.fields_by_name['torso'].message_type = _M3BASEHUMANOIDSTATUS
_M3HUMANOIDSTATUS.fields_by_name['head'].message_type = _M3BASEHUMANOIDSTATUS
_M3HUMANOIDCOMMAND.fields_by_name['right_arm'].message_type = _M3BASEHUMANOIDCOMMAND
_M3HUMANOIDCOMMAND.fields_by_name['left_arm'].message_type = _M3BASEHUMANOIDCOMMAND
_M3HUMANOIDCOMMAND.fields_by_name['torso'].message_type = _M3BASEHUMANOIDCOMMAND
_M3HUMANOIDCOMMAND.fields_by_name['head'].message_type = _M3BASEHUMANOIDCOMMAND
_M3HUMANOIDPARAM.fields_by_name['right_arm'].message_type = _M3BASEHUMANOIDPARAM
_M3HUMANOIDPARAM.fields_by_name['left_arm'].message_type = _M3BASEHUMANOIDPARAM
_M3HUMANOIDPARAM.fields_by_name['torso'].message_type = _M3BASEHUMANOIDPARAM
_M3HUMANOIDPARAM.fields_by_name['head'].message_type = _M3BASEHUMANOIDPARAM
_M3BASEHUMANOIDCOMMAND.fields_by_name['ctrl_mode'].enum_type = joint_array_mode_pb2._JOINT_ARRAY_MODE
_M3BASEHUMANOIDCOMMAND.fields_by_name['vias'].message_type = trajectory_pb2._M3JOINTVIA
_M3BASEHUMANOIDCOMMAND.fields_by_name['smoothing_mode'].enum_type = smoothing_mode_pb2._SMOOTHING_MODE

class M3HumanoidStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HUMANOIDSTATUS

class M3HumanoidCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HUMANOIDCOMMAND

class M3HumanoidParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3HUMANOIDPARAM

class M3BaseHumanoidStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3BASEHUMANOIDSTATUS

class M3BaseHumanoidCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3BASEHUMANOIDCOMMAND

class M3BaseHumanoidParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3BASEHUMANOIDPARAM

