# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_JOINT_ARRAY_MODE = descriptor.EnumDescriptor(
  name='JOINT_ARRAY_MODE',
  full_name='JOINT_ARRAY_MODE',
  filename='JOINT_ARRAY_MODE',
  values=[
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_OFF', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_PWM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_TORQUE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_TORQUE_GC', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA_GC', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA_MJ', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_THETA_GC_MJ', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_SPLINED_TRAJ', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_SPLINED_TRAJ_GC', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_TORQUE_SHM', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_ARRAY_MODE_ANGLE_SHM', index=11, number=11,
      options=None,
      type=None),
  ],
  options=None,
)


JOINT_ARRAY_MODE_OFF = 0
JOINT_ARRAY_MODE_PWM = 1
JOINT_ARRAY_MODE_TORQUE = 2
JOINT_ARRAY_MODE_THETA = 3
JOINT_ARRAY_MODE_TORQUE_GC = 4
JOINT_ARRAY_MODE_THETA_GC = 5
JOINT_ARRAY_MODE_THETA_MJ = 6
JOINT_ARRAY_MODE_THETA_GC_MJ = 7
JOINT_ARRAY_MODE_SPLINED_TRAJ = 8
JOINT_ARRAY_MODE_SPLINED_TRAJ_GC = 9
JOINT_ARRAY_MODE_TORQUE_SHM = 10
JOINT_ARRAY_MODE_ANGLE_SHM = 11




