# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3JOINTARRAYSTATUS = descriptor.Descriptor(
  name='M3JointArrayStatus',
  full_name='M3JointArrayStatus',
  filename='joint_array.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3JointArrayStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='motor_temp', full_name='M3JointArrayStatus.motor_temp', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amp_temp', full_name='M3JointArrayStatus.amp_temp', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='current', full_name='M3JointArrayStatus.current', index=3,
      number=4, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torque', full_name='M3JointArrayStatus.torque', index=4,
      number=5, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torquedot', full_name='M3JointArrayStatus.torquedot', index=5,
      number=6, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta', full_name='M3JointArrayStatus.theta', index=6,
      number=7, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadot', full_name='M3JointArrayStatus.thetadot', index=7,
      number=8, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadotdot', full_name='M3JointArrayStatus.thetadotdot', index=8,
      number=9, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='completed_spline_idx', full_name='M3JointArrayStatus.completed_spline_idx', index=9,
      number=10, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pwm_cmd', full_name='M3JointArrayStatus.pwm_cmd', index=10,
      number=11, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='M3JointArrayStatus.flags', index=11,
      number=12, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3JOINTARRAYCOMMAND = descriptor.Descriptor(
  name='M3JointArrayCommand',
  full_name='M3JointArrayCommand',
  filename='joint_array.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tq_desired', full_name='M3JointArrayCommand.tq_desired', index=0,
      number=1, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pwm_desired', full_name='M3JointArrayCommand.pwm_desired', index=1,
      number=2, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_stiffness', full_name='M3JointArrayCommand.q_stiffness', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ctrl_mode', full_name='M3JointArrayCommand.ctrl_mode', index=3,
      number=4, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vias', full_name='M3JointArrayCommand.vias', index=4,
      number=5, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_desired', full_name='M3JointArrayCommand.q_desired', index=5,
      number=6, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pos_desired', full_name='M3JointArrayCommand.pos_desired', index=6,
      number=7, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qdot_desired', full_name='M3JointArrayCommand.qdot_desired', index=7,
      number=8, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_slew_rate', full_name='M3JointArrayCommand.q_slew_rate', index=8,
      number=9, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='smoothing_mode', full_name='M3JointArrayCommand.smoothing_mode', index=9,
      number=10, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3JOINTARRAYPARAM = descriptor.Descriptor(
  name='M3JointArrayParam',
  full_name='M3JointArrayParam',
  filename='joint_array.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3JointArrayParam.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2
import trajectory_pb2
import joint_pb2
import smoothing_mode_pb2
import joint_array_mode_pb2

_M3JOINTARRAYSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3JOINTARRAYCOMMAND.fields_by_name['ctrl_mode'].enum_type = joint_array_mode_pb2._JOINT_ARRAY_MODE
_M3JOINTARRAYCOMMAND.fields_by_name['vias'].message_type = trajectory_pb2._M3JOINTVIA
_M3JOINTARRAYCOMMAND.fields_by_name['smoothing_mode'].enum_type = smoothing_mode_pb2._SMOOTHING_MODE

class M3JointArrayStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTARRAYSTATUS

class M3JointArrayCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTARRAYCOMMAND

class M3JointArrayParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTARRAYPARAM

