# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_JOINT_MODE_ROS = descriptor.EnumDescriptor(
  name='JOINT_MODE_ROS',
  full_name='JOINT_MODE_ROS',
  filename='JOINT_MODE_ROS',
  values=[
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_ROS_OFF', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_ROS_THETA', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_ROS_THETA_GC', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


JOINT_MODE_ROS_OFF = 0
JOINT_MODE_ROS_THETA = 1
JOINT_MODE_ROS_THETA_GC = 2




