# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_JOINT_MODE = descriptor.EnumDescriptor(
  name='JOINT_MODE',
  full_name='JOINT_MODE',
  filename='JOINT_MODE',
  values=[
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_OFF', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_PWM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_TORQUE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_THETA', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_TORQUE_GC', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_THETA_GC', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_THETA_MJ', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOINT_MODE_THETA_GC_MJ', index=7, number=7,
      options=None,
      type=None),
  ],
  options=None,
)


JOINT_MODE_OFF = 0
JOINT_MODE_PWM = 1
JOINT_MODE_TORQUE = 2
JOINT_MODE_THETA = 3
JOINT_MODE_TORQUE_GC = 4
JOINT_MODE_THETA_GC = 5
JOINT_MODE_THETA_MJ = 6
JOINT_MODE_THETA_GC_MJ = 7



_M3JOINTSTATUS = descriptor.Descriptor(
  name='M3JointStatus',
  full_name='M3JointStatus',
  filename='joint.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3JointStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='motor_temp', full_name='M3JointStatus.motor_temp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amp_temp', full_name='M3JointStatus.amp_temp', index=2,
      number=3, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='current', full_name='M3JointStatus.current', index=3,
      number=4, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torque', full_name='M3JointStatus.torque', index=4,
      number=6, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torquedot', full_name='M3JointStatus.torquedot', index=5,
      number=7, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta', full_name='M3JointStatus.theta', index=6,
      number=8, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadot', full_name='M3JointStatus.thetadot', index=7,
      number=9, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadotdot', full_name='M3JointStatus.thetadotdot', index=8,
      number=10, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torque_gravity', full_name='M3JointStatus.torque_gravity', index=9,
      number=11, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pwm_cmd', full_name='M3JointStatus.pwm_cmd', index=10,
      number=12, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ambient_temp', full_name='M3JointStatus.ambient_temp', index=11,
      number=13, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='case_temp', full_name='M3JointStatus.case_temp', index=12,
      number=14, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='power', full_name='M3JointStatus.power', index=13,
      number=15, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='M3JointStatus.flags', index=14,
      number=16, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3JOINTPARAM = descriptor.Descriptor(
  name='M3JointParam',
  full_name='M3JointParam',
  filename='joint.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='kq_p', full_name='M3JointParam.kq_p', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kq_i', full_name='M3JointParam.kq_i', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kq_d', full_name='M3JointParam.kq_d', index=2,
      number=3, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kq_i_limit', full_name='M3JointParam.kq_i_limit', index=3,
      number=4, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_q', full_name='M3JointParam.max_q', index=4,
      number=5, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_q', full_name='M3JointParam.min_q', index=5,
      number=6, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kt_p', full_name='M3JointParam.kt_p', index=6,
      number=7, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kt_i', full_name='M3JointParam.kt_i', index=7,
      number=8, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kt_d', full_name='M3JointParam.kt_d', index=8,
      number=9, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kt_i_limit', full_name='M3JointParam.kt_i_limit', index=9,
      number=10, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kq_g', full_name='M3JointParam.kq_g', index=10,
      number=11, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_q_slew_rate', full_name='M3JointParam.max_q_slew_rate', index=11,
      number=12, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kq_i_range', full_name='M3JointParam.kq_i_range', index=12,
      number=13, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kt_i_range', full_name='M3JointParam.kt_i_range', index=13,
      number=14, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_q_pad', full_name='M3JointParam.max_q_pad', index=14,
      number=15, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_q_pad', full_name='M3JointParam.min_q_pad', index=15,
      number=16, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3JOINTCOMMAND = descriptor.Descriptor(
  name='M3JointCommand',
  full_name='M3JointCommand',
  filename='joint.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tq_desired', full_name='M3JointCommand.tq_desired', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_desired', full_name='M3JointCommand.q_desired', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pwm_desired', full_name='M3JointCommand.pwm_desired', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_stiffness', full_name='M3JointCommand.q_stiffness', index=3,
      number=4, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ctrl_mode', full_name='M3JointCommand.ctrl_mode', index=4,
      number=5, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qdot_desired', full_name='M3JointCommand.qdot_desired', index=5,
      number=6, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_slew_rate', full_name='M3JointCommand.q_slew_rate', index=6,
      number=7, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='brake_off', full_name='M3JointCommand.brake_off', index=7,
      number=8, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='smoothing_mode', full_name='M3JointCommand.smoothing_mode', index=8,
      number=9, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2
import smoothing_mode_pb2

_M3JOINTSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3JOINTCOMMAND.fields_by_name['ctrl_mode'].enum_type = _JOINT_MODE
_M3JOINTCOMMAND.fields_by_name['smoothing_mode'].enum_type = smoothing_mode_pb2._SMOOTHING_MODE

class M3JointStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTSTATUS

class M3JointParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTPARAM

class M3JointCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3JOINTCOMMAND

