# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3LEDMATRIXECSTATUS = descriptor.Descriptor(
  name='M3LedMatrixEcStatus',
  full_name='M3LedMatrixEcStatus',
  filename='led_matrix_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3LedMatrixEcStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ethercat', full_name='M3LedMatrixEcStatus.ethercat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3LedMatrixEcStatus.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='debug', full_name='M3LedMatrixEcStatus.debug', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='M3LedMatrixEcStatus.flags', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3LEDMATRIXECRGB = descriptor.Descriptor(
  name='M3LedMatrixEcRGB',
  full_name='M3LedMatrixEcRGB',
  filename='led_matrix_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='r', full_name='M3LedMatrixEcRGB.r', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='g', full_name='M3LedMatrixEcRGB.g', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='b', full_name='M3LedMatrixEcRGB.b', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3LEDMATRIXECRGBROW = descriptor.Descriptor(
  name='M3LedMatrixEcRGBRow',
  full_name='M3LedMatrixEcRGBRow',
  filename='led_matrix_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='column', full_name='M3LedMatrixEcRGBRow.column', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3LEDMATRIXECCOMMAND = descriptor.Descriptor(
  name='M3LedMatrixEcCommand',
  full_name='M3LedMatrixEcCommand',
  filename='led_matrix_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='enable', full_name='M3LedMatrixEcCommand.enable', index=0,
      number=1, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='row', full_name='M3LedMatrixEcCommand.row', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3LEDMATRIXECPARAM = descriptor.Descriptor(
  name='M3LedMatrixEcParam',
  full_name='M3LedMatrixEcParam',
  filename='led_matrix_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='slew_rate', full_name='M3LedMatrixEcParam.slew_rate', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2

_M3LEDMATRIXECSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3LEDMATRIXECSTATUS.fields_by_name['ethercat'].message_type = component_base_pb2._M3ETHERCATSTATUS
_M3LEDMATRIXECRGBROW.fields_by_name['column'].message_type = _M3LEDMATRIXECRGB
_M3LEDMATRIXECCOMMAND.fields_by_name['row'].message_type = _M3LEDMATRIXECRGBROW

class M3LedMatrixEcStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECSTATUS

class M3LedMatrixEcRGB(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECRGB

class M3LedMatrixEcRGBRow(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECRGBROW

class M3LedMatrixEcCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECCOMMAND

class M3LedMatrixEcParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LEDMATRIXECPARAM

