# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3LOADX1STATUS = descriptor.Descriptor(
  name='M3LoadX1Status',
  full_name='M3LoadX1Status',
  filename='loadx1.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3LoadX1Status.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torque', full_name='M3LoadX1Status.torque', index=1,
      number=6, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torquedot', full_name='M3LoadX1Status.torquedot', index=2,
      number=7, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3LOADX1PARAM = descriptor.Descriptor(
  name='M3LoadX1Param',
  full_name='M3LoadX1Param',
  filename='loadx1.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dummy', full_name='M3LoadX1Param.dummy', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3LOADX1COMMAND = descriptor.Descriptor(
  name='M3LoadX1Command',
  full_name='M3LoadX1Command',
  filename='loadx1.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dummy', full_name='M3LoadX1Command.dummy', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2

_M3LOADX1STATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS

class M3LoadX1Status(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX1STATUS

class M3LoadX1Param(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX1PARAM

class M3LoadX1Command(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3LOADX1COMMAND

