# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_ROBOT_MONITOR_STATE = descriptor.EnumDescriptor(
  name='ROBOT_MONITOR_STATE',
  full_name='ROBOT_MONITOR_STATE',
  filename='ROBOT_MONITOR_STATE',
  values=[
    descriptor.EnumValueDescriptor(
      name='ROBOT_MONITOR_OKAY', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROBOT_MONITOR_LOW_WARN', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROBOT_MONITOR_HIGH_WARN', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROBOT_MONITOR_LOW_ERR', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROBOT_MONITOR_HIGH_ERR', index=4, number=4,
      options=None,
      type=None),
  ],
  options=None,
)


ROBOT_MONITOR_OKAY = 0
ROBOT_MONITOR_LOW_WARN = 1
ROBOT_MONITOR_HIGH_WARN = 2
ROBOT_MONITOR_LOW_ERR = 3
ROBOT_MONITOR_HIGH_ERR = 4



_M3ROBOTMONITORCOMPONENTSTATUS = descriptor.Descriptor(
  name='M3RobotMonitorComponentStatus',
  full_name='M3RobotMonitorComponentStatus',
  filename='robot_monitor.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='component_name', full_name='M3RobotMonitorComponentStatus.component_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='M3RobotMonitorComponentStatus.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg', full_name='M3RobotMonitorComponentStatus.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3ROBOTMONITORSTATUS = descriptor.Descriptor(
  name='M3RobotMonitorStatus',
  full_name='M3RobotMonitorStatus',
  filename='robot_monitor.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3RobotMonitorStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='volt_comp', full_name='M3RobotMonitorStatus.volt_comp', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temp_comp', full_name='M3RobotMonitorStatus.temp_comp', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3ROBOTMONITORCOMMAND = descriptor.Descriptor(
  name='M3RobotMonitorCommand',
  full_name='M3RobotMonitorCommand',
  filename='robot_monitor.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='force_safe_op', full_name='M3RobotMonitorCommand.force_safe_op', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3ROBOTMONITORCOMPONENTPARAM = descriptor.Descriptor(
  name='M3RobotMonitorComponentParam',
  full_name='M3RobotMonitorComponentParam',
  filename='robot_monitor.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='max_val_warn', full_name='M3RobotMonitorComponentParam.max_val_warn', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_val_warn', full_name='M3RobotMonitorComponentParam.min_val_warn', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_val_err', full_name='M3RobotMonitorComponentParam.max_val_err', index=2,
      number=3, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='min_val_err', full_name='M3RobotMonitorComponentParam.min_val_err', index=3,
      number=4, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='component_name', full_name='M3RobotMonitorComponentParam.component_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3ROBOTMONITORPARAM = descriptor.Descriptor(
  name='M3RobotMonitorParam',
  full_name='M3RobotMonitorParam',
  filename='robot_monitor.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='volt_comp', full_name='M3RobotMonitorParam.volt_comp', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='temp_comp', full_name='M3RobotMonitorParam.temp_comp', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2

_M3ROBOTMONITORCOMPONENTSTATUS.fields_by_name['state'].enum_type = _ROBOT_MONITOR_STATE
_M3ROBOTMONITORSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3ROBOTMONITORSTATUS.fields_by_name['volt_comp'].message_type = _M3ROBOTMONITORCOMPONENTSTATUS
_M3ROBOTMONITORSTATUS.fields_by_name['temp_comp'].message_type = _M3ROBOTMONITORCOMPONENTSTATUS
_M3ROBOTMONITORPARAM.fields_by_name['volt_comp'].message_type = _M3ROBOTMONITORCOMPONENTPARAM
_M3ROBOTMONITORPARAM.fields_by_name['temp_comp'].message_type = _M3ROBOTMONITORCOMPONENTPARAM

class M3RobotMonitorComponentStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3ROBOTMONITORCOMPONENTSTATUS

class M3RobotMonitorStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3ROBOTMONITORSTATUS

class M3RobotMonitorCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3ROBOTMONITORCOMMAND

class M3RobotMonitorComponentParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3ROBOTMONITORCOMPONENTPARAM

class M3RobotMonitorParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3ROBOTMONITORPARAM

