# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_SMOOTHING_MODE = descriptor.EnumDescriptor(
  name='SMOOTHING_MODE',
  full_name='SMOOTHING_MODE',
  filename='SMOOTHING_MODE',
  values=[
    descriptor.EnumValueDescriptor(
      name='SMOOTHING_MODE_OFF', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SMOOTHING_MODE_SLEW', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SMOOTHING_MODE_MIN_JERK', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


SMOOTHING_MODE_OFF = 0
SMOOTHING_MODE_SLEW = 1
SMOOTHING_MODE_MIN_JERK = 2




