# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3TACTILEPPS22ECSTATUS = descriptor.Descriptor(
  name='M3TactilePPS22EcStatus',
  full_name='M3TactilePPS22EcStatus',
  filename='tactile_pps22_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3TactilePPS22EcStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ethercat', full_name='M3TactilePPS22EcStatus.ethercat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3TactilePPS22EcStatus.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='taxels', full_name='M3TactilePPS22EcStatus.taxels', index=3,
      number=4, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3TACTILEPPS22ECCOMMAND = descriptor.Descriptor(
  name='M3TactilePPS22EcCommand',
  full_name='M3TactilePPS22EcCommand',
  filename='tactile_pps22_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dummy', full_name='M3TactilePPS22EcCommand.dummy', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3TACTILEPPS22ECPARAM = descriptor.Descriptor(
  name='M3TactilePPS22EcParam',
  full_name='M3TactilePPS22EcParam',
  filename='tactile_pps22_ec.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='config', full_name='M3TactilePPS22EcParam.config', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2

_M3TACTILEPPS22ECSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3TACTILEPPS22ECSTATUS.fields_by_name['ethercat'].message_type = component_base_pb2._M3ETHERCATSTATUS

class M3TactilePPS22EcStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TACTILEPPS22ECSTATUS

class M3TactilePPS22EcCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TACTILEPPS22ECCOMMAND

class M3TactilePPS22EcParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TACTILEPPS22ECPARAM

