# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_M3TORQUESHMBASESTATUS = descriptor.Descriptor(
  name='M3TorqueShmBaseStatus',
  full_name='M3TorqueShmBaseStatus',
  filename='torque_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='torque', full_name='M3TorqueShmBaseStatus.torque', index=0,
      number=1, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theta', full_name='M3TorqueShmBaseStatus.theta', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thetadot', full_name='M3TorqueShmBaseStatus.thetadot', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ctrl_mode', full_name='M3TorqueShmBaseStatus.ctrl_mode', index=3,
      number=4, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='loadx6', full_name='M3TorqueShmBaseStatus.loadx6', index=4,
      number=5, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3TORQUESHMBASECOMMAND = descriptor.Descriptor(
  name='M3TorqueShmBaseCommand',
  full_name='M3TorqueShmBaseCommand',
  filename='torque_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tq_desired', full_name='M3TorqueShmBaseCommand.tq_desired', index=0,
      number=1, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='q_desired', full_name='M3TorqueShmBaseCommand.q_desired', index=1,
      number=2, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='slew_rate_q_desired', full_name='M3TorqueShmBaseCommand.slew_rate_q_desired', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3TORQUESHMSTATUS = descriptor.Descriptor(
  name='M3TorqueShmStatus',
  full_name='M3TorqueShmStatus',
  filename='torque_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='base', full_name='M3TorqueShmStatus.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_arm', full_name='M3TorqueShmStatus.right_arm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_arm', full_name='M3TorqueShmStatus.left_arm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torso', full_name='M3TorqueShmStatus.torso', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='M3TorqueShmStatus.head', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_hand', full_name='M3TorqueShmStatus.right_hand', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3TORQUESHMCOMMAND = descriptor.Descriptor(
  name='M3TorqueShmCommand',
  full_name='M3TorqueShmCommand',
  filename='torque_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='M3TorqueShmCommand.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_arm', full_name='M3TorqueShmCommand.right_arm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='left_arm', full_name='M3TorqueShmCommand.left_arm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='torso', full_name='M3TorqueShmCommand.torso', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='head', full_name='M3TorqueShmCommand.head', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='right_hand', full_name='M3TorqueShmCommand.right_hand', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_M3TORQUESHMPARAM = descriptor.Descriptor(
  name='M3TorqueShmParam',
  full_name='M3TorqueShmParam',
  filename='torque_shm.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='test', full_name='M3TorqueShmParam.test', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import component_base_pb2
import joint_array_mode_pb2

_M3TORQUESHMBASESTATUS.fields_by_name['ctrl_mode'].enum_type = joint_array_mode_pb2._JOINT_ARRAY_MODE
_M3TORQUESHMSTATUS.fields_by_name['base'].message_type = component_base_pb2._M3BASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['right_arm'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['left_arm'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['torso'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['head'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMSTATUS.fields_by_name['right_hand'].message_type = _M3TORQUESHMBASESTATUS
_M3TORQUESHMCOMMAND.fields_by_name['right_arm'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['left_arm'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['torso'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['head'].message_type = _M3TORQUESHMBASECOMMAND
_M3TORQUESHMCOMMAND.fields_by_name['right_hand'].message_type = _M3TORQUESHMBASECOMMAND

class M3TorqueShmBaseStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMBASESTATUS

class M3TorqueShmBaseCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMBASECOMMAND

class M3TorqueShmStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMSTATUS

class M3TorqueShmCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMCOMMAND

class M3TorqueShmParam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _M3TORQUESHMPARAM

