"""autogenerated by genpy from shm_led_mouth/LEDMatrixRow.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import shm_led_mouth.msg

class LEDMatrixRow(genpy.Message):
  _md5sum = "5a0313057dae76e530e4ef99ceb0eca4"
  _type = "shm_led_mouth/LEDMatrixRow"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """LEDMatrixRGB column
================================================================================
MSG: shm_led_mouth/LEDMatrixRGB
uint32 r
uint32 g
uint32 b
"""
  __slots__ = ['column']
  _slot_types = ['shm_led_mouth/LEDMatrixRGB']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       column

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LEDMatrixRow, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.column is None:
        self.column = shm_led_mouth.msg.LEDMatrixRGB()
    else:
      self.column = shm_led_mouth.msg.LEDMatrixRGB()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.column.r, _x.column.g, _x.column.b))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.column is None:
        self.column = shm_led_mouth.msg.LEDMatrixRGB()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.column.r, _x.column.g, _x.column.b,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.column.r, _x.column.g, _x.column.b))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.column is None:
        self.column = shm_led_mouth.msg.LEDMatrixRGB()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.column.r, _x.column.g, _x.column.b,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
